In [1]:
import pandas as pd
import csv
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori

In [2]:
path_res='german_encoded.csv'
dataset = []
with open(path_res) as csv_file:
    csv_reader = csv.reader(csv_file, delimiter=',')
    for row in csv_reader:
        dataset.append(row)

In [3]:
te = TransactionEncoder()
te_ary = te.fit(dataset).transform(dataset)
df = pd.DataFrame(te_ary, columns=te.columns_)
frequent_itemsets = apriori(df, min_support=0.2, use_colnames=True)

frequent_itemsets

      support                                    itemsets
0       0.907                                      (A101)
1       0.274                                       (A11)
2       0.308                                      (A112)
3       0.413                                      (A114)
4       0.269                                       (A12)
...       ...                                         ...
2080    0.202        (A171, A191, A211, A143, A201, A173)
2081    0.217   (A152, A101, A171, A143, A201, A32, A161)
2082    0.232  (A152, A101, A171, A211, A143, A201, A173)
2083    0.209   (A101, A171, A32, A143, A201, A173, A161)
2084    0.219   (A101, A171, A32, A143, A201, A211, A161)

[2085 rows x 2 columns]

In [4]:
from mlxtend.frequent_patterns import association_rules

association_rules(frequent_itemsets, metric="confidence", min_threshold=0.2)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(A101),(A11),0.907,0.274,0.238,0.262404,0.957677,-0.010518,0.984278
1,(A11),(A101),0.274,0.907,0.238,0.868613,0.957677,-0.010518,0.707833
2,(A101),(A112),0.907,0.308,0.278,0.306505,0.995146,-0.001356,0.997844
3,(A112),(A101),0.308,0.907,0.278,0.902597,0.995146,-0.001356,0.954800
4,(A101),(A114),0.907,0.413,0.380,0.418964,1.014440,0.005409,1.010264
...,...,...,...,...,...,...,...,...,...
31851,(A32),"(A101, A171, A211, A201, A143, A161)",0.530,0.283,0.219,0.413208,1.460097,0.069010,1.221897
31852,(A143),"(A101, A171, A211, A201, A32, A161)",0.814,0.251,0.219,0.269042,1.071880,0.014686,1.024682
31853,(A201),"(A101, A171, A211, A143, A32, A161)",0.963,0.228,0.219,0.227414,0.997431,-0.000564,0.999242
31854,(A211),"(A101, A171, A143, A201, A32, A161)",0.700,0.319,0.219,0.312857,0.980743,-0.004300,0.991060
31855,(A161),"(A101, A171, A211, A143, A201, A32)",0.633,0.236,0.219,0.345972,1.465981,0.069612,1.168145

In [8]:
rules = association_rules(frequent_itemsets, min_threshold=0.2)
rules
#export_csv = rules.to_csv('Rules.csv')

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(A101),(A11),0.907,0.274,0.238,0.262404,0.957677,-0.010518,0.984278
1,(A11),(A101),0.274,0.907,0.238,0.868613,0.957677,-0.010518,0.707833
2,(A101),(A112),0.907,0.308,0.278,0.306505,0.995146,-0.001356,0.997844
3,(A112),(A101),0.308,0.907,0.278,0.902597,0.995146,-0.001356,0.954800
4,(A101),(A114),0.907,0.413,0.380,0.418964,1.014440,0.005409,1.010264
...,...,...,...,...,...,...,...,...,...
31851,(A32),"(A101, A171, A211, A201, A143, A161)",0.530,0.283,0.219,0.413208,1.460097,0.069010,1.221897
31852,(A143),"(A101, A171, A211, A201, A32, A161)",0.814,0.251,0.219,0.269042,1.071880,0.014686,1.024682
31853,(A201),"(A101, A171, A211, A143, A32, A161)",0.963,0.228,0.219,0.227414,0.997431,-0.000564,0.999242
31854,(A211),"(A101, A171, A143, A201, A32, A161)",0.700,0.319,0.219,0.312857,0.980743,-0.004300,0.991060
31855,(A161),"(A101, A171, A211, A143, A201, A32)",0.633,0.236,0.219,0.345972,1.465981,0.069612,1.168145

In [29]:
rules["antecedent_len"] = rules["antecedents"].apply(lambda x: len(x))
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,antecedent_len
0,(A61),(A11),0.603,0.274,0.219,0.363184,1.325489,0.053778,1.140047,1
1,(A11),(A61),0.274,0.603,0.219,0.799270,1.325489,0.053778,1.977782,1
2,(A121),(A191),0.282,0.596,0.204,0.723404,1.213766,0.035928,1.460615,1
3,(A191),(A121),0.596,0.282,0.204,0.342282,1.213766,0.035928,1.091653,1
4,(A93),(A133),0.548,0.315,0.211,0.385036,1.222338,0.038380,1.113887,1
...,...,...,...,...,...,...,...,...,...,...
2931,"(A32, A211)","(A161, A171, A101, A143, A201)",0.361,0.409,0.219,0.606648,1.483247,0.071351,1.502472,2
2932,"(A32, A143)","(A161, A171, A101, A211, A201)",0.452,0.333,0.219,0.484513,1.454995,0.068484,1.293923,2
2933,"(A201, A32)","(A161, A171, A101, A211, A143)",0.510,0.293,0.219,0.429412,1.465569,0.069570,1.239072,2
2934,(A161),"(A171, A32, A101, A211, A143, A201)",0.633,0.236,0.219,0.345972,1.465981,0.069612,1.168145,1
2935,(A32),"(A161, A171, A101, A211, A143, A201)",0.530,0.283,0.219,0.413208,1.460097,0.069010,1.221897,1

In [30]:
rules[ (rules['antecedent_len'] >= 2) &
       (rules['confidence'] > 0.75) &
       (rules['lift'] > 1.2) ]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,antecedent_len
18,"(A14, A101)",(A211),0.373,0.700,0.331,0.887399,1.267714,0.069900,2.664286,2
22,"(A32, A101)",(A161),0.472,0.633,0.427,0.904661,1.429164,0.128224,3.849422,2
26,"(A34, A101)",(A211),0.268,0.700,0.226,0.843284,1.204691,0.038400,1.914286,2
35,"(A201, A11)",(A61),0.259,0.603,0.208,0.803089,1.331822,0.051823,2.016137,2
48,"(A132, A32)",(A161),0.258,0.633,0.236,0.914729,1.445069,0.072686,4.303909,2
...,...,...,...,...,...,...,...,...,...,...
2882,"(A171, A32, A211, A143, A201)","(A161, A101)",0.258,0.573,0.219,0.848837,1.481391,0.071166,2.824769,5
2883,"(A32, A101, A211, A143, A201)","(A161, A171)",0.264,0.550,0.219,0.829545,1.508264,0.073800,2.640000,5
2894,"(A32, A211, A101, A171)","(A201, A161, A143)",0.282,0.501,0.219,0.776596,1.550091,0.077718,2.233619,4
2897,"(A32, A211, A143, A171)","(A201, A161, A101)",0.272,0.555,0.219,0.805147,1.450715,0.068040,2.283774,4
2900,"(A32, A211, A101, A143)","(A201, A161, A171)",0.276,0.531,0.219,0.793478,1.494309,0.072444,2.270947,4

In [11]:
rules1 = rules[rules['consequents'] == {'A211'}]
rules1

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
41,(A101),(A211),0.907,0.7,0.635,0.700110,1.000158,0.0001,1.000368
89,(A112),(A211),0.308,0.7,0.211,0.685065,0.978664,-0.0046,0.952577
105,(A114),(A211),0.413,0.7,0.289,0.699758,0.999654,-0.0001,0.999194
133,(A121),(A211),0.282,0.7,0.222,0.787234,1.124620,0.0246,1.410000
149,(A123),(A211),0.332,0.7,0.230,0.692771,0.989673,-0.0024,0.976471
...,...,...,...,...,...,...,...,...,...
30984,"(A171, A201, A143, A161, A173)",(A211),0.295,0.7,0.206,0.698305,0.997579,-0.0005,0.994382
31167,"(A171, A143, A201, A32, A161)",(A211),0.350,0.7,0.240,0.685714,0.979592,-0.0050,0.954545
31293,"(A171, A191, A201, A143, A173)",(A211),0.290,0.7,0.202,0.696552,0.995074,-0.0010,0.988636
31481,"(A152, A101, A171, A201, A143, A173)",(A211),0.299,0.7,0.232,0.775920,1.108457,0.0227,1.338806
31731,"(A101, A171, A143, A201, A32, A161)",(A211),0.319,0.7,0.219,0.686520,0.980743,-0.0043,0.957000

In [12]:
rules2 = rules[rules['consequents'] == {'A212'}]
rules2

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
43,(A101),(A212),0.907,0.3,0.272,0.299890,0.999632,-0.0001,0.999843
224,(A143),(A212),0.814,0.3,0.224,0.275184,0.917281,-0.0202,0.965763
295,(A161),(A212),0.633,0.3,0.200,0.315956,1.053186,0.0101,1.023326
335,(A171),(A212),0.848,0.3,0.255,0.300708,1.002358,0.0006,1.001012
421,(A201),(A212),0.963,0.3,0.296,0.307373,1.024576,0.0071,1.010645
471,(A61),(A212),0.603,0.3,0.217,0.359867,1.199558,0.0361,1.093523
864,"(A143, A101)",(A212),0.742,0.3,0.204,0.274933,0.916442,-0.0186,0.965428
1148,"(A101, A171)",(A212),0.770,0.3,0.229,0.297403,0.991342,-0.0020,0.996303
1364,"(A101, A201)",(A212),0.880,0.3,0.269,0.305682,1.018939,0.0050,1.008183
2544,"(A143, A201)",(A212),0.782,0.3,0.222,0.283887,0.946292,-0.0126,0.977500
3536,"(A171, A201)",(A212),0.821,0.3,0.251,0.305725,1.019082,0.0047,1.008246
4010,"(A61, A201)",(A212),0.581,0.3,0.213,0.366609,1.222031,0.0387,1.105163
5948,"(A143, A101, A201)",(A212),0.718,0.3,0.202,0.281337,0.937790,-0.0134,0.974031
7771,"(A101, A171, A201)",(A212),0.751,0.3,0.226,0.300932,1.003107,0.0007,1.001333

In [17]:
rules_filt = rules1.append(rules2, ignore_index=False)
rules_filt

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
41,(A101),(A211),0.907,0.7,0.635,0.700110,1.000158,0.0001,1.000368
89,(A112),(A211),0.308,0.7,0.211,0.685065,0.978664,-0.0046,0.952577
105,(A114),(A211),0.413,0.7,0.289,0.699758,0.999654,-0.0001,0.999194
133,(A121),(A211),0.282,0.7,0.222,0.787234,1.124620,0.0246,1.410000
149,(A123),(A211),0.332,0.7,0.230,0.692771,0.989673,-0.0024,0.976471
...,...,...,...,...,...,...,...,...,...
2544,"(A143, A201)",(A212),0.782,0.3,0.222,0.283887,0.946292,-0.0126,0.977500
3536,"(A171, A201)",(A212),0.821,0.3,0.251,0.305725,1.019082,0.0047,1.008246
4010,"(A61, A201)",(A212),0.581,0.3,0.213,0.366609,1.222031,0.0387,1.105163
5948,"(A143, A101, A201)",(A212),0.718,0.3,0.202,0.281337,0.937790,-0.0134,0.974031
7771,"(A101, A171, A201)",(A212),0.751,0.3,0.226,0.300932,1.003107,0.0007,1.001333

In [18]:
export_csv = rules_filt.to_csv('Rules_filt.csv')